version: "3.7"

volumes:
    DB_VOLUME:
    MINIO_VOLUME:
    FTP_VOLUME:

services:
    db:
        image: mariadb:10.6
        restart: always
        working_dir: /srv
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: ftp_production
        ports:
            - 3306:3306
        volumes:
            - DB_VOLUME:/var/lib/mysql
            - ./dbscripts:/srv/scripts

    minio:
        image: minio/minio:latest
        restart: always
        entrypoint: sh
        ports:
            - 9000:9000
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: -c 'mkdir -p /data/fromthepage && /usr/bin/minio server /data'
        volumes:
            - MINIO_VOLUME:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    ftp:
        image: fromthepage:latest
        restart: always
        environment:
            SERVER_HOSTNAME: "localhost"
            RAILS_ENV: production
            # ensure these params match whatever you defined for the db up top
            DATABASE_URL: mysql2://root:${MYSQL_ROOT_PASSWORD}@db/ftp_production
            SMTP_ENABLED: "false"
            SMTP_SERVER: ""
            SMTP_PORT: 587
            SMTP_USERNAME: ""
            SMTP_PASSWORD: ""
            SMTP_DOMAIN: ""
            ADMIN_EMAILS: "you@yourdomain.com, other-email@yourdomain.com"
            SENDING_EMAIL_ADDRESS: "fromthepage-support@yourdomain.com"
            USE_PNG_LOGO: "false"
            GUEST_DEED_COUNT: 3
            GUEST_TRANSCRIPTION_ENABLED: "false"
            FACEBOOK_PIXEL_ID: ""
            MIXPANEL_ID: ""
            GA_ACCOUNT: ""
            ENABLE_GOOGLEOAUTH: ""
            GOOGLE_CLIENT_ID: ""
            GOOGLE_CLIENT_SECRET: ""
            ENABLE_SAML: "false"
            RECAPTCHA_SITE_KEY: ""
            RECAPTCHA_SECRET_KEY: ""
            INTERCOM_APP_ID: ""
            INTERCOM_ACCESS_TOKEN: ""
            MINIO_ACCESS_KEY: ""
            MINIO_SECRET_KEY: ""
        working_dir: /srv/fromthepage
        command: "bash -x /srv/fromthepage/start.sh"
        volumes:
            - FTP_VOLUME:/srv/fromthepage/public
            - ./fromthepage/config/storage.yml:/srv/fromthepage/config/storage.yml
            - ./fromthepage/config/environments/production.rb:/srv/fromthepage/config/environments/production.rb
            - ./fromthepage/config/initializers/01fromthepage.rb:/srv/fromthepage/config/initializers/01fromthepage.rb
        ports:
            - 3000:3000

    edge:
        image: nginx:latest
        restart: always
        volumes:
            - FTP_VOLUME:/srv/fromthepage/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
